console.log("The Blacklist");
console.log("Clarice");
console.log("24 Tv show");
console.log("Hells Kitchen");
console.log("CSI Vegas");
console.log("CSI New York");
console.log("CSI Miami");
console.log("CSI Cyber");
console.log("The Rookie");
console.log("The Arrow");
console.log("The Flash");
console.log("Nurses");
